### PR TITLE
Fix Arabic names of Gregorian months

### LINKED ISSUE #116: Arabic names of Gregorian months should be Syriac
**Describe the bug**
Arabic names of Gregorian months should be Syriac, not Latin, like كَانُون ٱلثَّانِي, شُبَاط, etc. and not يناير, etc.

**To Reproduce**
1. Go to an event in Arabic, like [this](https://www.josa.ngo/ar/events/115/editing-arabic-wikipedia).
2. See dates in the side box.

**Expected behavior**
The month name in Arabic 'فبراير' should be 'شباط'. Other events have the same issue.

### PR DESCRIPTION
**Pull request by alsahawneh**
Fixes #116.

### CODE REVIEW

File: plugins/datetime-filter.js [hunk 1]
```diff
@@ -66,9 +66,10 @@ const dayFullDate = (dt, lang) => {
  * E.g. for locale 'en-UK' returns 'Saturday, 5 February 2022'
  */
 const fullDateWithTimeZone = (date, timeZoneString, locale) => {
+  const jordanLocale = languageToLocale(locale)
```
Comment (thread-koder) [inline plugins/datetime-filter.js:69]: @alsahawneh Please change the name of the variable to "langToLocale", because it's not just for the Arabic language
