### PR TITLE
Fix wrong page padding in Partners page

### LINKED ISSUE #182: Wrong page padding in Partners page
**Describe the bug**
On mobile devices / small screens, a space is shown on the side of the 'Partners' page.

**To Reproduce**
1. Go to the Partners page at https://josa.ngo/ar/partners-and-supporters
£. See error

**Expected behavior**
The content should extend to the whole page / content in small screens / mobile.

**Screenshot**

### PR DESCRIPTION
**Pull request by alsahawneh**
Fixes #182.

### CODE REVIEW

File: components/Partners/PartnerPreview.vue [hunk 1]
```diff
@@ -4,9 +4,9 @@
       v-if="partner.logo"
       :image="partner.logo"
       size="medium"
-      class="thumbnail"
+      class="thumbnail flex-none"
```
Comment (mahasneh) [inline components/Partners/PartnerPreview.vue:7]: Can you double check this? The spacing is caused by the `mr-6` and `ml-6`utilities in the `.preview .thumbnail` directives, not because of `flex` shrinking.

**Review by mahasneh — CHANGES_REQUESTED** [review]

File: components/Partners/PartnerPreview.vue (hunk 1 above)
Comment (alsahawneh) [reply components/Partners/PartnerPreview.vue:7]: Will fix it ASAP.

Comment (alsahawneh) [reply components/Partners/PartnerPreview.vue]: @mahasneh I have done the requested changes.
