### PR TITLE
Fix wrong padding in Single Career page

### LINKED ISSUE #181: Wrong page padding in 'Career' single pages
**Describe the bug**
On mobile devices / small screens, a space is shown on the side of the single pages of careers.

**To Reproduce**
1. Go to a career page like 'https://josa.ngo/careers/15/communications-assistant'
3. See error

**Expected behavior**
The content should extend to the whole page / content in small screens / mobile.

**Screenshot**

### PR DESCRIPTION
**Pull request by alsahawneh**
Fixes #181.

### CODE REVIEW

File: components/Careers/CareerSingle.vue [hunk 1]
```diff
@@ -12,7 +12,7 @@
           </p>
         </div>
         <div class="content flex flex-wrap md:flex-nowrap mt-12">
-          <div class="w-full md:w-3/5 ltr:mr-8 rtl:ml-8 mb-8">
+          <div class="w-full md:w-3/5 lg:ltr:mr-8 lg:rtl:ml-8 mb-8">
```
Comment (mahasneh) [inline components/Careers/CareerSingle.vue:15]: This should be `md:ltr:mr-8` and `md:rtl:ml-8` as the breakpoint is on `md` not `lg`

**Review by mahasneh — CHANGES_REQUESTED** [review]

File: components/Careers/CareerSingle.vue (hunk 1 above)
Comment (alsahawneh) [reply components/Careers/CareerSingle.vue:15]: Ok. Will fix it ASAP.

Comment (alsahawneh) [reply components/Careers/CareerSingle.vue]: Done. @mahasneh check it out!
